version: "3"
services:
  myjenkins:
    build: ./
    container_name: myjenkins
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      - TARGET_ENV=development
    volumes:
      - my-jenkins-volume:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  my-jenkins-volume:
