version: "3"
services:
  mynginx:
    build: ./
    container_name: mynginx
    ports:
      - 9090:80
    environment:
      - TARGET_ENV=development
    volumes:
      - "/home/docker/nginx:/usr/share/nginx/html"